### ISSUE TITLE
Implement a header section

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#13]
Visual Aid: <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">Figma File</a> and <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit">Google Doc</a>

Implement the hero section containing:
- [ ] "**Welcome to Algorithmia SE**"
- [ ] "**Coding The Future, Bringing Ideas Into Reality**"
- [ ] _The paragraph_ "**Our expanding consortium of ALX Software Engineering students, representing all cohorts, is fervently committed to transforming innovative ideas into reality, and fearlessly conquering real-life challenges.**"
- [ ] A button saying: "**Join Our Consortium**"

**Comment by Ukasquared** [comment]
I will like to do the hero section, But I have a little challenge with the figma page not opening

**Comment by dohoudaniel** [comment]
Hi @Ukasquared.
Thank you for volunteering to work on this part of the file.
Please, note that the Figma file, actually opens.
Please try another means to open up the Figma file.
However, this task will be assigned to you.
Thank you once again 😊.,

**Comment by Algorithmia-SE-2023** [comment]
Thank you @Ukasquared for volunteering again.
@EmyCodes @TeamKweku @samuelogboye @reecevinto @jailan-sh
You have all been assigned to work on these tasks together with @Ukasquared.

Kindly note:
**The deadline for this task is on or before _3rd of October, 2023_**

Facing any issues?
Reach out to @ALX-SE-Algorithmia/code-reviewing-team

**Comment by EmyCodes** [comment]
Wow. It's a privilege to offer my quota. Thanks for the opportunity.

**Comment by dohoudaniel** [comment]
Thank you for implementing the solution.
Your PR has been merged accordingly.
