### ISSUE TITLE
Implement the section: "Our Journey"

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#14]
Visual Aid: <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">Figma File</a> and <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit">Google Doc</a>

Implement the section for Our Journey

**Comment by Dprof-code** [comment]
I would like to work on this.

**Comment by sshdopey** [comment]
No no @Dprof-code let soemone take on this issue, you're working on soem issues already

**Comment by Dprof-code** [comment]
Okay.

**Comment by Algorithmia-SE-2023** [comment]
@shazaaly @Femshot @Mubarak1A @ValCaite @MartyOfMCA @el898 
You have all been assigned to work on these tasks together.

**Kindly note, the deadline for this issue is on or before the _4th of October, 2023_**

**Facing any issues?**
Reach out to @ALX-SE-Algorithmia/code-reviewing-team.

**Comment by shazaaly** [comment]
Noted

**Comment by Mubarak1A** [comment]
Noted

**Comment by ValCaite** [comment]
Noted
