### ISSUE TITLE
Implement the section: Our Mission and Our Vision

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#15]
Visual Aid: <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">Figma File</a> and <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit">Google Doc</a>

Implement the:
- [ ] Our Mission section
- [ ] Our Vision section

**Comment by Algorithmia-SE-2023** [comment]
@valentino7504 @Adams2004 @Namujibril @Chima-01 @Youngman-d-coder @SamuelWorld20
You have all been assigned to work on this issue together.

Kindly note:
**The deadline for this issue is on or before the _4th of October, 2023_.**

**Facing any issues?**
Kindly reach out to @ALX-SE-Algorithmia/code-reviewing-team.

**Comment by Youngman-d-coder** [comment]
The work is about implementing the cards like sections side by side?

**Comment by Algorithmia-SE-2023** [comment]
Yes.

**Comment by Chima-01** [comment]
hey @Adams2004 can I get your collab link again?

**Comment by Catercodes** [comment]
Ok No problem
