### ISSUE TITLE
Implement section: "Goals"

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#16]
Visual Aid: <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">Figma File</a> and <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit">Google Doc</a>

Implement the goals in the "Goals" section:
- [ ] Header: Goals
- [ ] Subheader: Coding The Future, Bringing Ideas Into Reality

Implement the following goals using the <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">visual Figma aid</a>:
- [ ] Diverse Collaboration
- [ ] Skill Enhancement
- [ ] Impactful Projects
- [ ] Community Growth
- [ ] Knowledge Sharing
- [ ] Open Source Advocacy
- [ ] Global Impact

**Comment by Dprof-code** [comment]
@Algorithmia-SE-2023 I would love to implement the Goals section.

**Comment by Dprof-code** [comment]
> @Algorithmia-SE-2023 I would love to implement the Goals section.

@DestinedCodes @dohoudaniel

**Comment by sshdopey** [comment]
It's assigned to you

**Comment by Algorithmia-SE-2023** [comment]
@Bigizic @chisomchinaza @Hullaah @Endygrit @2023rahabu 
You have all been assigned to work on these tasks together with @Dprof-code.

Kindly note:
**The deadline for the issue is on or before _4th of October 2023_**

**Facing any issues?**
Kindly reach out to @ALX-SE-Algorithmia/code-reviewing-team.

**Comment by Bigizic** [comment]
Roger

**Comment by 2023rahabu** [comment]
Hello team please am new to Figma is there any tutorial on this, please

**Comment by Algorithmia-SE-2023** [comment]
Hi @2023rahabu. You don't really need to know how to use Figma files for this project.
In my current knowledge, all you need is the presentation (<a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">attached here</a>) to give you an idea of how what we need to implement looks like.

**Comment by 2023rahabu** [comment]
Ohh thank you so much for your clarification

**Comment by Bigizic** [comment]
The google doc requires special permission, you might need to set it to whoever with the link ![image](https://github.com/ALX-SE-Algorithmia/ALX-SE-Algorithmia.github.io/assets/117412923/d1458566-25e7-4423-98c5-2fedb920f52a)
