### ISSUE TITLE
Implement footer section

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#17]
Visual Aid: <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">Figma File</a> and <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit">Google Doc</a>

Implement the footer section:

The footer section contains:

A "**Contact Us**" section using Iconscout Icons:
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=GitHub" target="_blank">GitHub Icon</a> for <a href="https://github.com/ALX-SE-Algorithmia" target="_blank">GitHub Organization Link</a> (Opens in new tab ( target="_blank") )
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=Twitter" target="_blank">Twitter Icon</a> for <a href="https://twitter.com/Algorithmia_SE" target="_blank">Twitter</a> (Opens in new tab ( target="_blank") )
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=Email" target="_blank">Email Icon</a> for <a href="mailto:algorithmiasecollaborators@gmail.com" target="_blank">Algorithmia SE's email</a> (Opens in new tab ( target="_blank") )
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=LinkedIn" target="_blank">LinkedIn icon</a> for <a href="https://www.linkedin.com/in/algorithmia-se-0743b9283/" target="_blank">Algorithmia SE's LinkedIn account</a> (Prompt to follow) (Opens in new tab ( target="_blank") )
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=Discord" target="_blank">Discord Icon</a> to join <a href="https://discord.gg/xgEsBQBRp3" target="_blank">Algorithmia SE's Discord server</a> (Opens in new tab ( target="_blank") )
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=WhatsApp" target="_blank">WhatsApp icon</a> to join <a href="https://whatsapp.com/channel/0029Va5SC3G9sBIFUjjzNl1c" target="_blank">Algorithmia SE's WhatsApp Channel</a> (Opens in new tab ( target="_blank") )
- [ ] <a href="https://iconscout.com/unicons/free-line-icons?query=YouTube" target="_blank">YouTube Icon</a> for <a href="https://www.youtube.com/@Algorithmia_SE" target="_blank">Algorithmia SE's YouTube Channel</a> (Opens in new tab ( target="_blank") )

**Comment by rodgersxy** [comment]
i want to contribute to this footer section @Algorithmia-SE-2023

**Comment by sshdopey** [comment]
It's assigned to tou

**Comment by TechDanny** [comment]
Hello, I want to work on the footer section

**Comment by dohoudaniel** [comment]
Hi @TechDanny.
You and @rodgersxy could work on it together.
I'll co-assign you now.

**Comment by Algorithmia-SE-2023** [comment]
@dohoudaniel @Anniedevkiller @DestinedCodes @Manuelshub
You have all been assigned to work on this issue with @TechDanny and @rodgersxy.

Kindly note:
**The deadline for this project is on or before the _5th of October, 2023_**

**Facing any issues?**
Kindly reach out to @ALX-SE-Algorithmia/code-reviewing-team.

**Comment by Manuelshub** [comment]
Hey @dohoudaniel Can I make use of font awesome for the icons??

**Comment by Anniedevkiller** [comment]
Ok

**Comment by dohoudaniel** [comment]
@Manuelshub we are using Iconscout Fonts or Google Fonts for them.
Please, let's use these ones.
There's also a very useful PR made by @rodgersxy for the footer. Check it out <a href="https://github.com/ALX-SE-Algorithmia/ALX-SE-Algorithmia.github.io/pull/22">here</a>.
I believe it will be very helpful for us.
Once again, well-done @rodgersxy.
