### ISSUE TITLE
Testing how to work on issues collaboratively

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#25]
This is a demo of how we will be working on GitHub issues.
Let's create some, shall we:
- [x] Create a file DUPLICATE_README.md
- [x] Create a file REAME.html
- [x] Create a file DANIEL.html file.

@dohoudaniel @dohoudaniel01 and @Algorithmia-SE-2023.
You have all been chosen to work on this issue together.

**Comment by dohoudaniel** [comment]
Hi @Algorithmia-SE-2023.
I have successfully created the three files, as stated in the GitHub issue, and I have also created a pull request.

**Comment by Algorithmia-SE-2023** [comment]
Now, we wait for our PR to be reviewed and merged.
