### ISSUE TITLE
Inappropriate Use of Semantic HTML5 Elements

### ISSUE THREAD

**Issue by Dprof-code** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#39]
- the closing head tag is coming after the body tag
- the <main> tag should wrap the whole elements in the body, that is the opening <main> tag should be after the closing </header> tag and the closing </main> should come before the opening footer tag.
- 
suggestions:
- the different sections should be wrapped in the <section> tag so as to improve easy code maintenance, accessibility and SEO.
- the images without alt property should have alt properties.

**Comment by Dprof-code** [comment]
@dohoudaniel @ALX-SE-Algorithmia/code-reviewing-team

**Comment by dohoudaniel** [comment]
@Dprof-code Please work on this, and fix it using a PR.
It has been assigned to you.
