### ISSUE TITLE
Project Page

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#40]
@ekerejosh @coApollo @ValCaite @chisomchinaza @Astro175 @KabzaKole
You have been assigned along with your team lead @masha-a-m to work on the Project Page.
@dohoudaniel will be your moderator.

<strong>Visual Aid</strong>
- <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=26-51&t=lrwFyeZhwBIg7MNw-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=541%3A379&mode=design">Projects Page (Figma)</a>
- <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit?usp=sharing">Website Details</a>
- <a href="https://docs.google.com/document/d/1_qXUmBQZF0VNnnbqzfpFUAMfp7oapNmFq1OTxzSGCxE/edit?usp=sharing">Google Doc (Projects Page)</a>
- <a href="https://youtu.be/Qeibe59f72s">YouTube Video</a>

The "Subscribe to our newsletter" and footer will be implemented by the team working on the Home Page. You don't need to worry about this part.

**Comment by KabzaKole** [comment]
I would like to contribute on the project page. However, I have not been assigned to the group.

**Comment by Algorithmia-SE-2023** [comment]
You have also been assigned too.

**Comment by 2023rahabu** [comment]
Hello @masha-a-m @dohoudaniel I have sent a pull request on issue 40 hope you received it. Thank you

**Comment by masha-a-m** [comment]
Hello @ALX-SE-Algorithmia/code-reviewing-team 
The project team has created the files as stated in the GitHub Issue and also created a pull request.
