### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#41]
@evanceodoyo @Collins331 @Ukasquared @Chima-01 @Akos-1 @kelechukwufavour
You have been assigned to work on the Blog page, with your team lead @SamuelWorld20, and your moderator @Anniedevkiller.

<strong>Visual Aid:</strong>
- <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=217-149&t=QYinztsDNlaHi6Xl-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=541%3A379&mode=design">Blog Page (Figma)</a>
- <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit?usp=sharing">Website Details</a>
- <a href="https://youtu.be/Qeibe59f72s">YouTube Video</a>

Please keep in mind that we are to implement the structure and the Figma file. The blogs will be added and communicated with you by @ALX-SE-Algorithmia/documentation-and-technical-writing-team.

The "Subscribe to our newsletter" and footer will be implemented by the team working on the Home Page. You don't need to worry about this part.

**Comment by Ukasquared** [comment]
Please I need a link to the article for this project and also pictures , except I am supposed to use random pictures

**Comment by Algorithmia-SE-2023** [comment]
Closed with PR #68
