### ISSUE TITLE
Home Page (Completion)

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#43]
A great job well-done on implementing the HTML for the Home page.
@rodgersxy @Dprof-code @chykB @Maryanemwende @flexywork327 @TechDanny
Thank you for your active contribution.

However, we need to round up the page and make it come to life, by adding the CSS, JS, and the other rest.
@Mubarak1A will be your team lead, and @dohoudaniel will be your team's moderator.

@Dprof-code, we are waiting for your solution to #39. This will help speed the process of development.

This **[Google Doc](https://docs.google.com/document/d/1JgMHYXD9Xw_LqmQ3-lg4CTv4KzjlWt7oqPhIxUoOCvA/edit?usp=sharing)** contains everything we need to implement in the home page.

**Visual Aid:**
- <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=541-379&t=mSpiguRB4NRl4hQ1-0&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=34%3A488">Home Page (Figma)</a>
- <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit?usp=sharing">Website Details (Google Doc)</a>
- <a href="https://docs.google.com/document/d/1JgMHYXD9Xw_LqmQ3-lg4CTv4KzjlWt7oqPhIxUoOCvA/edit?usp=sharing">Home Page (Google Doc)</a>
- <a href="https://youtu.be/Qeibe59f72s">YouTube Video</a>

**Comment by Dprof-code** [comment]
Yes I would work on it today.
