### ISSUE TITLE
Structuring the project and energizing the date

### ISSUE THREAD

**Issue by WassCodeur** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#57]
I've noticed that the project is not structured, all the html files are directly in the root folder. In addition the date in the footer in static we can make it dynamic with js

**Describe the solution you'd like**
My solution consists in reorganizing the projects by putting only the index.html file in the root and all the other .html files in the src/ folder and all those concerning style, images, js, etc. in the assets folder. as for dynamizing the date, I'm planning to use js so that the date can adapt to the current year.

**Additional context**
![image](https://github.com/ALX-SE-Algorithmia/ALX-SE-Algorithmia.github.io/assets/100234404/5a4fc4b1-23bd-4f1e-9d3a-59f5737a9256)

![image](https://github.com/ALX-SE-Algorithmia/ALX-SE-Algorithmia.github.io/assets/100234404/334c03ef-426c-4ca7-a453-be2da8b154c1)

**Comment by Algorithmia-SE-2023** [comment]
Hi @WassCodeur.
Thank you so much for your contribution to this project, and once again, welcome to the community.
However, please note that this request will be closed.
Reasons are:

We already have a structure we are following for the static web project, and it will be disastrous to adjust to these changes now, as we approach the end of this very project.
This suggestion shall be followed in the next project.
Once again, thank you @WassCodeur, and welcome to the Algorithmia SE 🌍 community.
Your contributions are highly valued.

Courtesy:
The @ALX-SE-Algorithmia/code-reviewing-team .
