### ISSUE TITLE
Text and Image Link Mismatch

### ISSUE THREAD

**Issue by joshua-ketor** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#69]
On [blog page](https://github.com/ALX-SE-Algorithmia/ALX-SE-Algorithmia.github.io/blob/main/blogs.html), line 149 is supposed to be in the div.article_link container on line 147.
@ALX-SE-Algorithmia/code-reviewing-team

**Comment by dohoudaniel** [comment]
Closed with #70.
