### ISSUE TITLE
Implement a navbar in index.html

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#8]
The navbar will contain all links to navigate the website, and the website logo:
1. Name: Algorithmia SE 🌏
2. Home page: A link to the index.html page
3. About Us: A link to the about.html page
4. Projects: A link to the projects.html page (The project page will contain a button that links to our Hashnode blog)
5. Events: A link to the events.html
6. Contact Us: A link to the contact.html page
7. Join Us: A button that links to the google form to be filled to join Algorithmia SE 🌏

**Comment by chykB** [comment]
@ALX-SE-Algorithmia/code-reviewing-team I would love to implement the nav section of the page. Thanks as I await your response.

**Comment by TechDanny** [comment]
@ALX-SE-Algorithmia/code-reviewing-team  I’d love to contribute in the implementation of the navbar section

**Comment by ActuaryEmma** [comment]
I would love to contribute

**Comment by Maryanemwende** [comment]
@ALX-SE-Algorithmia/code-reviewing-team I would love to contribute to the navbar implementation

**Comment by masha-a-m** [comment]
Hello @ALX-SE-Algorithmia/code-reviewing-team  
I would love to contribute to the navbar section

**Comment by Ukasquared** [comment]
I would love to work on the navigation bar.

**Comment by Ukasquared** [comment]
@ALX-SE-Algorithmia/code-reviewing-team I would love to work on the navigation bar

**Comment by rodgersxy** [comment]
@ALX-SE-Algorithmia/code-reviewing-team Hi, i would like to contribute to this section

**Comment by Algorithmia-SE-2023** [comment]
Hi everyone.
@chykB @TechDanny @ActuaryEmma @Maryanemwende @masha-a-m @Ukasquared @rodgersxy.
Thank you for your volunteering spirit.
However, this issue will be closed, and another set be open.
Thank you.
