### ISSUE TITLE
Implement a div in the index.html file

### ISSUE THREAD

**Issue by Algorithmia-SE-2023** [Algorithmia-SE/ALX-SE-Algorithmia.github.io#9]
Implement a div that contains the following:
1. Wrap the text "**Algorithmia SE 🌏**" in a span.
2. Wrap "**Trailblazing Tech Excellence, ALX SE Style**" in an h1, h2, h3 or h4 tag.
3. Wrap "**Coding The Future, Bringing Ideas Into Reality**" in an h1 or h2 tag.
4. Wrap "**Our expanding consortium of ALX Software Engineering students, representing all cohorts, is fervently committed to transforming innovative ideas into reality, and fearlessly real-life challenges**" in a span.
5. Create a button, the content of the button: "**Join Our Consortium**"

Wrapping all this in a div container, it will help while designing the colors in CSS.

**Comment by Mubarak1A** [comment]
@Algorithmia-SE-2023, would love to work on this

**Comment by masha-a-m** [comment]
Hello @ALX-SE-Algorithmia/code-reviewing-team 
I would love to work on this section

**Comment by Arewa01** [comment]
@ALX-SE-Algorithmia/code-reviewing-team i'd love to work on this

**Comment by Algorithmia-SE-2023** [comment]
Hi @Mubarak1A @masha-a-m @Arewa01.
Thank you for volunteering to work on this section.
However, this issue will be closed, and other improved issues be open.
Thank you all 🤍.
